name: pricelet_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  floor: ^1.4.2
  flutter:
    sdk: flutter
  intl: ^0.18.1
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
